"""days to hire table

Revision ID: 5c36e361377d
Revises: d8758e455bf2
Create Date: 2025-06-27 13:35:15.807605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c36e361377d'
down_revision = 'd8758e455bf2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('days_to_hire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('standard_job_id', sa.String(), nullable=False),
    sa.Column('average_days_to_hire', sa.Float(), nullable=True),
    sa.Column('minimum_days_to_hire', sa.Float(), nullable=True),
    sa.Column('maximum_days_to_hire', sa.Float(), nullable=True),
    sa.Column('number_of_job_postings', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('days_to_hire', schema='public')
    # ### end Alembic commands ###
